config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root "users#index"

  resources :users
  resources :values, only: [:index]
  resources :inspirations, only: [:index]
  resources :goals do
    resources :steps

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :steps

  validates :title, presence: true
  validates :description, presence: true
  validates :deadline, presence: true
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :user
  belongs_to :goal

  validates :description, presence: true
  validates :deadline, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :goals
  has_many :steps

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 validates :username, presence: true, length: { minimum: 4, maximum: 16 }
 validates :first_name, presence: true
 validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!
  def index
    @goals = current_user.goals.all
  end

  def show
    @goal = Goal.find(params[:id])
    @steps = @goal.steps
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    if @goal.save
      redirect_to goals_path
      flash[:success] = "Hooray #{current_user.first_name}! You created a new career goal!"
    else
      @goal.errors.any?
      flash[:error] =  @goal.errors.full_messages.join(", ")
      render :new
    end
  end

  protected

  def goal_params
    params.require(:goal).permit(:title, :description, :deadline)
  end
end

app/controllers/inspirations_controller.rb
class InspirationsController < ApplicationController
  def index
  end 
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :first_name, :last_name, :username, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :first_name, :last_name, :username, :password, :password_confirmation, :current_password)
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
    before_action :authenticate_user!

    def index
      @goal = Goal.find(params[:goal_id])
      @steps = Step.all
      redirect_to @goal
    end

    def show
      @goal = Goal.find(params[:goal_id])
      @step = Step.find(params[:id])
    end

    def new
      @step = Step.new
      @goal = Goal.find(params[:goal_id])
    end

    def create
      @goal = Goal.find(params[:goal_id])
      @step = Step.new(step_params)
      @step.goal = @goal
      @step.user_id = current_user.id
      if @step.save
        redirect_to goal_path(@goal)
        flash[:success] = "Hooray #{current_user.first_name}! You created a new step!"
      else
        @step.errors.any?
        flash[:error] =  @step.errors.full_messages.join(", ")
        render :new
      end
    end

    protected

    def step_params
      params.require(:step).permit(:description, :deadline)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/values_controller.rb
class ValuesController < ApplicationController
  def index
    @values = ["Variety and change", "Be an expert", "Help others",
      "Compete with others", "Express creativity", "Be challenged",
    "Be recognized", "Be wealthy", "Flexible schedule", "Vacation time" ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<div id="goals_index">
  <h1>MY CAREER GOALS</h1>
  <div class="goal_list">
    <ul>
      <% counter = 0 %>
      <% @goals.each do |goal| %>
      <% counter += 1 %>
        <% unless current_user.nil? %>
        <% end %>
         <li class="goal"><%="#{counter}.) "%><%= link_to("#{goal.title}", goal) %></li>
      <% end %>
    </ul>
  </div>
  <div class="index link">
    <%= button_to "Create a Career Goal", new_goal_path, method: :get %>
  </div>
</div>

app/views/goals/new.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });
</script>
<div id="new_goal">
<h1 class="new_goal_header">NEW CAREER GOAL</h1>
<%= form_for(@goal) do |f| %>

<div class="goal_form">
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description%><br>

  <%= f.label :deadline %><br>
  <%= f.text_field :deadline, :type => "text", :id => "datepicker"  %><br>

  <%= f.submit "Add Career Goal" %>
</div>

<% end %>
</div>

<div class="footer">
  <%= link_to 'back to my goals', goals_path %>
</div>

app/views/goals/show.html.erb
<div id="goal">
  <div class="title">
    <h1 class="header"><%=@goal.title%></h1>
    <p class="description"><%=@goal.description%></p>
  </div>
  <div class="show_steps">
    <h4>Steps I Need to Take to Achieve My Goal :</h4>
    <ul>
      <% counter = 0 %>
      <% if @steps == nil %>
      <% @steps = "" %>
        <% else  @steps.each do |step| %>
        <% counter += 1 %>
        <li><%=counter%>.) <%= step.description %></li>
        <li class="step_deadline"><%= step.deadline %></li></br>
        <% end %>
        <% end %>
    </li>
    </ul>
  </div>
  <div class="goal_deadline"> </a>
    <h2>Finish This Goal Before: <%=@goal.deadline%></h2>
  </div>
  <div class="link">
    <a class="linka"><%= button_to 'Create New Steps for Goal', new_goal_step_path(@goal), method: :get%></a>
  </div>
</div>

app/views/inspirations/index.html.erb
<head>
  <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
</head>
<div id="inspiration">
  <h1>BE INSPIRED</h1>
  <h3>click a quote</h3>
  <div id="app"></div>
</div>

app/views/layouts/_navbar.html.erb
<nav id="navbar">
  <div class="logo">
    <a href="/"><%=image_tag("https://marketplace-cdn.atlassian.com/files/images/94f3969e-76bf-44f3-856f-8c03724c24e4.png")%></a>
    <h1 class="logoheader"><a href="/">Careerleon</a></h1>
  </div>
  <h3 class="logosub">making change happen</h3>
  <div class="links">
    <ul>
      <% if user_signed_in? %>
          <li class="signed-in">Signed in as <span class="username"><%= current_user[:username] %></span></li>
          <li><%= link_to 'Inspiration', inspirations_path %></li>
          <li><%= link_to 'Values', values_path %></li>
          <li><%= link_to 'My Goals', goals_path(current_user) %></li>
          <li><%= link_to 'My Account', user_path(current_user) %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'Inspiration', inspirations_path %></li>
          <li><%= link_to 'Values', values_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- #The line below needs to be uncommented when submitting to production -->
    <!-- <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> -->
    <title>Careerleon</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application" %>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Patrick+Hand" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bungee+Hairline" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bungee+Hairline|Dosis" rel="stylesheet">
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div id="flash">
      <% flash.each do |name, message| %>
        <%= content_tag :div, message, :id => "flash_#{name}" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/steps/index.html.erb
<div class="content">
  <div class="index_link">
    <%= link_to "new_step", new_step_path %>
  </div>
  <div class="step_list">
    <h4>MY STEPS</h4>
    <ul>
      <% @steps.each do |step| %>
        <% unless current_user.nil? %>
        <% end %>
         <li class="goal"><%="#{step.title}"%></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/steps/new.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });
</script>
<div id="new_step">
<h1>CREATE A NEW STEP</h1>
<%= form_for [@goal, @step] do |f| %>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, required: true, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.text_field :deadline, :type => "text", :id => "datepicker" %><br>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>

<% end %>
<%= link_to 'Back', goal_path(@goal) %>
</div>

app/views/users/index.html.erb
<div id="blog">
  <div class="blog_header">
    <h1>Careerleon Blog </h1>
    <h2>Are You Ready to Start a New Career?</h2>
  </div>
  <div class="blog_photo"><img src="/assets/employees.jpg")%></img></div>
  <p class="blog_text">You wake up, silence your alarm, and the idea of getting out of bed and going to work begins filling your head with anxiety.
    This is one reason why you should stop waiting and start your career transition now. There are many other viable reasons why you should make a change:
    lack of challenge, poor pay, or even lack of respect at the workplace. The reality is, as people we aren't born into a specific career.
    As difficult as it might seem to change your current job, it's possible. You made a decision to take your current job,
    and you can make the decision to leave it. Careerleon is here to help you on your journey into a new career. Create goals, set deadlines,
    and take the steps needed to achieve your goals. If you need to think about what you truly want in a career, click on values and take some time to ponder.
    If you need encouragement, click on inspiration and find a quote that will lead you to a better mindset. A better future is on its way!
  </p>
</div>

app/views/users/show.html.erb
<div id="profile">
  <h1>Welcome, <%=current_user.first_name%>!</h1>
  <p>Username: <%= current_user.username %></p>
  <p>Member: <%= current_user.first_name %> <%= current_user.last_name %></p>
  <p>Email: <%= current_user.email %></p>
  <p><%= button_to 'Edit Profile', edit_user_registration_path, method: :get %></p><br />
</div>

app/views/values/index.html.erb
<head>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.12.4.js"></script>
  <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<div id="values">
  <h1>WHAT DO YOU VALUE MOST IN A CAREER?</h1>
  <h3>drag your favorites into the cloud</h3>
  <div>
    <img class="droppable", src='/assets/cloud.png'></img>
</div>
<div class=javaValues></div>

  <% @values.each do |value| %>
    <div class="draggable">
      <li><%= "#{value}" %></br></li>
    </div>
  <% end %>
</div>

<script>
var valueArray = [];
var printValues = "";
$(function() {
 $( ".draggable" ).draggable();
 $( ".droppable" ).droppable({
 drop: function( event, ui ) {
    valueArray.push(ui.draggable.text());
    ui.draggable.fadeOut("slow");
    for (let value of valueArray) {
       valueArray.pop();
       printValues += value + "<br/>"
       $( ".javaValues" ).html("");
       $( ".javaValues" ).append("<h3>My Values:</h3>" + printValues + "<br/>");
    }
     $( this )
     .addClass( "ui-state-highlight" )
     .find( "img" )
    }
  });
});
</script>